version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: synergysphere
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/synergysphere"
      JWT_SECRET: "your-super-secret-jwt-key-here"
      CORS_ORIGIN: "http://localhost:5173"
      NODE_ENV: "development"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:5000"
      VITE_WS_URL: "http://localhost:5000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
